name: Makefile CI

on:
  push:
    # branches: [ master ]
    tags:
      - '*'
  # pull_request:
    # branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Get version
      run: |
        version=$(jq -r '.version' src/manifest.json)
        echo "Version: $version"
        echo "::set-output name=version::$version"

    - uses: actions/checkout@v2
      
    - name: Build Firefox
      run: make build.firefox
      
    - name: Build Chrome
      run: make build.chrome
    
    - name: Upload a Chrome Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        name: kudoall-chrome-${{ needs.build.outputs.version }}.zip
        path: build/artefacts/kudoall-chrome-${{ needs.build.outputs.version }}.zip

    - name: Upload a Firefox Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        name: kudoall-firefox-${{ needs.build.outputs.version }}.zip
        path: build/artefacts/kudoall-firefox-${{ needs.build.outputs.version }}.zip

    - uses: ncipollo/release-action@v1
      with:
        artifacts: "build/artefacts/kudoall-chrome-${{ needs.build.outputs.version }}.zip,build/artefacts/kudoall-firefox-${{ needs.build.outputs.version }}.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
